redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]
node_bundler = "esbuild"

[build]
publish = "C:\\Users\\User\\Downloads\\upload-this-syndesis"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/trigger"
to = "/.netlify/functions/trigger"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]