openapi: 3.0.1
info:
  title: SYNDESIS API
  description: Basic SYNDESIS plugin API for environment-based triggers
  version: "1.0.0"
servers:
  - url: https://syndesis.social
paths:
  /status:
    get:
      summary: Returns plugin status
      operationId: getStatus
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "active"
